services:
  - type: web
    name: BOOK_LIBRARY
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: BOOK_LIBRARY_DEV
          property: database
      - key: DB_USER
        fromDatabase:
          name: BOOK_LIBRARY_DEV
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: BOOK_LIBRARY_DEV
          property: password
      - key: DB_HOST
        fromDatabase:
          name: BOOK_LIBRARY_DEV
          property: host
      - key: DB_PORT
        fromDatabase:
          name: BOOK_LIBRARY_DEV
          property: port

databases:
  - name: BOOK_LIBRARY_DEV
    plan: free
    region: frankfurt
    databaseName: books
    ipAllowList: [] 