name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    env:

      DB_PASSWORD: 'password'
      DB_NAME: 'BOOK_LIBRARY_DEV'
      DB_USER: 'root'
      DB_HOST: 'localhost'
      DB_PORT: 3307
      Port: 3000
      DB_DIALECT: mysql2

# Your environment variables might be wrong. Please double check .env file
# Environment Variables are: {
#   DB_PASSWORD: 'password',
#   DB_NAME: 'BOOK_LIBRARY_DEV',
#   DB_USER: 'root',
#   DB_HOST: 'localhost',
#   DB_PORT: '3307'

    steps:


      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: docker-compose up -d ${DB_DIALECT}
      - run: docker run --link ${DIALECT}:db -e CHECK_PORT=${SEQ_PORT::-1} -e CHECK_HOST=db --net cli_default giorgos/takis
      - run: npm test

      - run: npm install sequelize@${{ matrix.sequelize-version }} 
