name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    env:
      DB_DATABASE: BOOK_LIBRARY_DEV
      DB_USER: root
      DB_PASSWORD: 'password'
      DB_HOST: localhost

    steps:

      - name: Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE BOOK_LIBRARY_DEV;' -uroot -ppassword
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
