name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    env:
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
        steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE wordpress_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
